// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEg8FvHejsvTzVNc652aiXQhaJtQKPnDM',
    appId: '1:110230623618:web:1c0042c2d61673b094ab9b',
    messagingSenderId: '110230623618',
    projectId: 'champions-8ca9d',
    authDomain: 'champions-8ca9d.firebaseapp.com',
    storageBucket: 'champions-8ca9d.appspot.com',
    measurementId: 'G-SJNSDPHYED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDouvSZG_mUIgiC5XPedLOlwr_vz31H2Us',
    appId: '1:110230623618:android:7f07857c433d7d2894ab9b',
    messagingSenderId: '110230623618',
    projectId: 'champions-8ca9d',
    storageBucket: 'champions-8ca9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1I_4kXrw71OiD7XvkdnHB-fWQ0ThT49Y',
    appId: '1:110230623618:ios:cefc046e0593dbc794ab9b',
    messagingSenderId: '110230623618',
    projectId: 'champions-8ca9d',
    storageBucket: 'champions-8ca9d.appspot.com',
    iosBundleId: 'com.example.champions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1I_4kXrw71OiD7XvkdnHB-fWQ0ThT49Y',
    appId: '1:110230623618:ios:fafa60c6cf6a3c2494ab9b',
    messagingSenderId: '110230623618',
    projectId: 'champions-8ca9d',
    storageBucket: 'champions-8ca9d.appspot.com',
    iosBundleId: 'com.example.champions.RunnerTests',
  );
}
